trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'


parameters:
  - name: environment
    type: string
    default: 'production'
  - name: webAppName
    type: string
    default: 'TaskFlowApi'

stages:

# ---------------- BUILD STAGE ----------------
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    steps:

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build Project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

# ---------------- DEPLOY STAGE ----------------
- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:

  - deployment: DeployWebApp
    displayName: 'Deploy Web App'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: drop

          # ---------------- APPLY MIGRATIONS ----------------
          - task: DotNetCoreCLI@2
            displayName: 'Apply EF Core Migrations'
            inputs:
              command: 'custom'
              custom: 'ef database update'
              projects: '**/TaskFlow.Infrastructure.csproj'
              arguments: '--configuration $(buildConfiguration)'

          # ---------------- DEPLOY WEB APP ----------------
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appName: '${{ parameters.webAppName }}'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'
              appType: 'webApp'